class Config:
    CHATGPT_ENDPOINT = 'https://els-openai-hackathon-5.openai.azure.com/'
    DB_FILENAME = 'boolean-search-history.db'
    ASJC_JOURNALS_MAPPINGS_CSV_FILEPATH = 'resource/ASJC_journals.csv'
    ASJC_CLASSIFICATION_MAPPING_CSV_FILEPATH = 'resource/ASJC_classification_with_levels.csv'
    EXAMPLE_QUERIES_XLSX_FILEPATH = 'resource/examples_for_hackathon.xlsx'
    BOOLEAN_STRING_OUTPUT_FOLDER = 'output/boolean_string'
    VECTOR_QUERY_OUTPUT_FOLDER = 'output/vector_query'
    SI_BOOLEAN_STRING_MAPPING_FILEPATH = 'output/si_boolean_string_mappings.json'
    SI_VECTOR_QUERY_MAPPING_FILEPATH = 'output/si_vector_query_mappings.json'
